config/routes.rb
Delivery::Application.routes.draw do

  get "/desc" => "desc/orders#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => 'index#index'

  match '/404' => 'index#not_found'
  match '/success/:id' => 'index#success'
  match '/place/:id' => 'index#place'
  match "/ajax/:action" => 'ajax'
  match '/forms/:action' => 'forms'
  match '/license' => 'index#license'
  match '/partnership' => 'index#partnership'
  match '/vacancy' => 'index#vacancy'
  match '/contact' => 'index#contact'
  match '/welcome' => 'index#welcome'
  match '/gifts' => 'index#gifts'

  match '/profile/:action' => 'profile'
  match '/profile' => 'profile#info'
  match '/profile/gifts' => 'index#userGifts'

  match '/partner' => 'partner/orders#index'
  match '/partner/orders/:order_id/ajaxEdit' => 'partner/orders#ajaxEdit'
  match '/partner/orders/:order_id/ajax_roll_back' => 'partner/orders#ajax_roll_back'
  match '/partner/orders/sortIndex' => 'partner/orders#sortIndex'
  match '/partner/orders/ajaxPaginate' => 'partner/orders#ajaxPaginate'
  match '/partner/orders/:order_id/ajaxRecover' => 'partner/orders#ajaxRecover'
  match '/partner/orders/:order_id/ajaxAdopted' => 'partner/orders#ajaxAdopted'
  match '/desc/orders/:order_id/ajaxEdit' => 'desc/orders#ajaxEdit'
  match '/desc/orders/sortIndex' => 'desc/orders#sortIndex'
  match '/desc/orders/ajaxPaginate' => 'desc/orders#ajaxPaginate'
  match '/desc/orders/ajaxIndex'=>'desc/orders#ajaxIndex'
  match '/desc/orders/:order_id/ajaxChangeAddress'=>'desc/orders#ajaxChangeAddress'

  match '/desc/orders/:order_id/ajax_roll_back'=>'desc/orders#ajax_roll_back'
  match '/desc/orders/:order_id/ajaxRecover' => 'desc/orders#ajaxRecover'
  match '/desc/orders/:order_id/ajaxAdopted' => 'desc/orders#ajaxAdopted'
  namespace :partner do
    root :to => 'orders#index'
    match "/ajax/:action" => 'ajax'
    get 'options' => 'places#options'
    get 'options/ajaxOptions' => 'places#ajaxOptions'
    match 'options/addUser' => 'places#addUser'
    post 'options/ajaxUserSave/' => 'places#ajaxUserSave'
    get 'options/ajaxOptionsUsers' => 'places#ajaxOptionsUsers'
    get 'options/ajaxUserEdit' => 'places#ajaxUserEdit'
    match 'options/delete_user' => 'places#delete_user'
    match 'options/setAlerts' => 'places#setAlerts'
    get 'options/accordion' => 'places#accordion'
    #match 'options/ajaxhistory' => 'places#ajaxhistory'
    match 'finances/ajaxPrice'=>'finances#ajaxPrice'
    match 'finances/ajaxIndex'=>'finances#ajaxIndex'
    match 'finances/ajaxBreadcrumb'=>'finances#ajaxBreadcrumb'
    #match 'finances/:id/render_to_xls' =>'finances#render_to_xls'

    #match "/ajax/:action" => 'ajax'
    match "/statistics/:action" => 'statistics'
    match "/statistics" => 'statistics#index'

    resources :finances
    resources :orders do
      get 'ajaxAdd'
      match 'ajaxSubmit'
      match 'ajaxTransfer'
      match 'ajaxCancel'
      match 'ajaxDeliver'
    end
    resources :places do
      #end
      match 'specials/showPic' => 'specials#showPic'
      resources :specials
      resources :sections do
        resources :items
      end
    end
  end

=begin
  namespace :operator do
    resources :orders do
      get 'ajaxAdd'
      match 'submit'
      match 'transmit'
      match 'cancel_order'
      match 'cancel_submit'
    end
    resources :places do
    end
  end
=end

  namespace :desc do
    root :to => "desc#orders"
    match "/ajax/:action" => 'ajax'
    match "/statistics/:action" => 'statistics'
    #match "/statistics/:action/:tab" => 'statistics'
    match "/statistics" => 'statistics#index'
    resources :users
    resources :cities do
      resources :regions
      resources :metros
    end
    resources :orders do
      #match '' orders_region_id_select
      match 'ajaxAdd'
      match 'ajaxSubmit'
      match 'ajaxTransfer'
      match 'ajaxCancel'
      match 'ajaxDeliver'
    end
    match 'finances/ajaxPrice'=>'finances#ajaxPrice'
    match 'finances/ajaxIndex'=>'finances#ajaxIndex'
    match 'finances/ajaxBreadcrumb'=>'finances#ajaxBreadcrumb'
    match 'finances/:id/render_to_xls' =>'finances#render_to_xls'
    match 'finances/:id/send_report' =>'finances#send_report'
    match 'finances/:id/send_called_report' =>'finances#send_called_report'
    resources :finances
    resources :kitchens
    resources :specials
    resources :populars
    resources :partners do
      resources :places do
        resources :sections do
          resources :items
        end
      end
    end
    resources :gift_sections do
      resources :gifts
    end
    resources :usergifts
  end
  match "*path", :to => "application#not_found"
end

app/models/partner.rb
class Partner < ActiveRecord::Base
  scope :activated, where(:active => 1)
  belongs_to :user
  has_many :items, :through => :baskets
  #has_many :places , :dependent => :delete_all
  has_many :places , :dependent => :destroy
  has_many :finances, :through => :places
  has_many :orders, :through => :places
end

app/controllers/desc/partners_controller.rb
# encoding: utf-8
class Desc::PartnersController < ApplicationController

  before_filter :global_admins, :breadcrumbs
  layout 'desc'

  def breadcrumbs
    @bread = [['Главная', '/desc'], ['Партнеры', desc_partners_path]]
  end

  def index
    if params[:f] && params[:d]
      @partners = Partner.order(params[:f] + " " + params[:d])
    else
      @partners = Partner.all
    end
  end

  def show
    @partner = Partner.find(params[:id])
    @bread << [@partner.name]
  end

  def new
    @bread << ['Новый партнер']
    @partner = Partner.new
  end

  def edit
    @partner = Partner.find(params[:id])
    @bread << [@partner.name]
  end

  def create

    #Создаем нового юзера
    if params[:radio1]=='2'
      params[:user][:phone] = '+7 ' +  params[:user][:phone]
      if User.exists?(:phone=>params[:user][:phone])
        flash[:notice] = 'Такой телефон уже зарегестрирован в базе'
        redirect_to(new_desc_partner_url, notice: 'User phone is exist.') and return
        #render action: "new"
        #redirect_to '/desc/partners/new'
      else
        user=User.new({
                          :phone =>params[:user][:phone],
                          :first_name =>params[:user][:first_name],
                          :email =>params[:user][:email]
                      })

        user.password=params[:user][:password]
        user.save

        params[:partner][:user_id]=user.id
      end
    end

    if params[:radio1] == '0'
      params[:partner][:user_id] = 0
    end

    if params[:partner_by_phone_check]=="1" && params[:partner_by_phone]!=""
      params[:partner][:by_phone] = "+7 " + params[:partner_by_phone].to_s
    else
      params[:partner][:by_phone] = ""
    end
    if params[:partner_by_email_check]=="1" && params[:partner_by_email]!=""
      params[:partner][:by_email] = params[:partner_by_email].to_s
    else
      params[:partner][:by_email] = ""
    end
    if params[:partner_by_sms_check]=="1" && params[:partner_by_sms]!=""
      params[:partner][:by_sms] = "+7 " + params[:partner_by_sms].to_s
    else
      params[:partner][:by_sms] = ""
    end
    if params[:report_by_phone_check]=="1" && params[:report_by_phone]!=""
      params[:partner][:report_by_phone] = "+7 " + params[:report_by_phone].to_s
    else
      params[:partner][:report_by_phone] = ""
    end
    if params[:report_by_email_check]=="1" && params[:report_by_email]!=""
      params[:partner][:report_by_email] = params[:report_by_email].to_s
    else
      params[:partner][:report_by_email] = ""
    end
    if params[:report_by_sms_check]=="1" && params[:report_by_sms]!=""
      params[:partner][:report_by_sms] = "+7 " + params[:report_by_sms].to_s
    else
      params[:partner][:report_by_sms] = ""
    end

    @partner = Partner.new(params[:partner])
    if params[:partner][:user_id].to_i > 0
      User.find(params[:partner][:user_id]).update_attribute(:access, 2)
    end
    if @partner.save
      redirect_to desc_partners_url, notice: 'Partner was successfully created.'
     # render :json=>{:params=>params}
    else
     render action: "new"
     # render :json=>{:params=>params}
    end
  end

  def update
    @partner = Partner.find(params[:id])
    olduid = @partner.user_id
    if params[:radio1]=='2'
      params[:user][:phone] = '+7 ' +  params[:user][:phone]
      if User.exists?(:phone=>params[:user][:phone])
        flash[:notice] = 'Такой телефон уже зарегестрирован в базе'
        redirect_to(edit_desc_partner_url(params[:id]), notice: 'User phone is exist.') and return
        #redirect_to '/desc/partners'
      else
        user=User.new({
                          :phone =>params[:user][:phone],
                          :first_name =>params[:user][:first_name],
                          :email =>params[:user][:email]
                      })

        user.password=params[:user][:password]

        if user.access.to_i <= 2 then
          user.access = 2
        end
        user.save

        params[:partner][:user_id]=user.id
        @partner.user_id = user.id
        @partner.save
        if olduid.to_i > 0
          setUserAccess olduid
        end
      end
    end

    if params[:radio1] == '0'
      @partner.update_attribute(:user_id, 0)
      if olduid.to_i > 0
        setUserAccess olduid
      end
    end

    if @partner.user_id.to_i > 0 && @partner.user_id.to_i != params[:partner][:user_id].to_i
      @partner.user_id = 0
      @partner.save
      if olduid.to_i > 0
        User.find(olduid).update_attribute(:access, 0)
        setUserAccess olduid
      end
      User.find(params[:partner][:user_id]).update_attribute(:access, 2)
    end

    if params[:partner_by_phone_check]=="1" && params[:partner_by_phone]!=""
      params[:partner][:by_phone] = "+7 " + params[:partner_by_phone].to_s
    else
      params[:partner][:by_phone] = ""
    end
    if params[:partner_by_email_check]=="1" && params[:partner_by_email]!=""
      params[:partner][:by_email] = params[:partner_by_email].to_s
    else
      params[:partner][:by_email] = ""
    end
    if params[:partner_by_sms_check]=="1" && params[:partner_by_sms]!=""
      params[:partner][:by_sms] = "+7 " + params[:partner_by_sms].to_s
    else
      params[:partner][:by_sms] = ""
    end
    if params[:report_by_phone_check]=="1" && params[:report_by_phone]!=""
      params[:partner][:report_by_phone] = "+7 " + params[:report_by_phone].to_s
    else
      params[:partner][:report_by_phone] = ""
    end
    if params[:report_by_email_check]=="1" && params[:report_by_email]!=""
      params[:partner][:report_by_email] = params[:report_by_email].to_s
    else
      params[:partner][:report_by_email] = ""
    end
    if params[:report_by_sms_check]=="1" && params[:report_by_sms]!=""
      params[:partner][:report_by_sms] = "+7 " + params[:report_by_sms].to_s
    else
      params[:partner][:report_by_sms] = ""
    end
    if @partner.update_attributes(params[:partner])
      redirect_to desc_partners_url, notice: 'Partner was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @partner = Partner.find(params[:id])

    users=[]

    @partner.places.each do |pl|
      pl.place_accesses.map{|p| users << p.user_id}
    end
    @partner.destroy

    users.uniq.each do |u|
      setUserAccess u
    end
    redirect_to desc_partners_url
  end

end

app/controllers/desc/places_controller.rb
# encoding: utf-8
class Desc::PlacesController < ApplicationController

  before_filter :global_admins, :breadcrumbs
  layout 'desc'

  def breadcrumbs
    partner = Partner.find(params[:partner_id])
    @bread = [['Главная', '/desc'], ['Партнеры', '/desc/partners'], [partner.name, edit_desc_partner_path(partner.id)], ['Заведения', desc_partner_places_path(params[:partner_id])]]
  end

  def index
    @places = Place.where(:partner_id => params[:partner_id])
    if params[:f] && params[:d]
      @places = @places.order(params[:f] + " " + params[:d])
    else
      @places = @places.all
    end
  end

  def show
    @place = Place.find(params[:id])
    @bread << [@place.name]
  end

  def new
    @bread << ['New']
    @place = Place.new
  end

  def edit
    @place = Place.find(params[:id])
    @bread << [@place.name]
  end

  def create
    if params[:place][:rating_minus].to_i > 0
      params[:place][:rating_minus] = params[:place][:rating_minus].to_i * -1
    end
    if params[:place][:rating_minus].to_i + params[:place][:rating_plus].to_i == 0
      params[:place][:rating] = 0
    else
      params[:place][:rating] = ((params[:place][:rating_plus].to_f / (params[:place][:rating_minus].to_f.abs + params[:place][:rating_plus].to_f.abs)) * 100).round
    end
    @place = Place.new(params[:place])
    @place.partner_id = params[:partner_id]
    if @place.save
      if params[:delivery]
        case params[:delivery]
          when "free"
            DeliveryPrice.where(:place_id => params[:id]).destroy_all
          when "region"
            DeliveryPrice.where(:place_id => params[:id]).destroy_all
            params[:delivery_region_new].each do |k, drn|
              if drn[:price] && drn[:price] != ""
                DeliveryPrice.create({:place_id => params[:id], :condition => "region", :price => drn[:price], :region_id => drn[:region]})
              end
            end
        end
      end
      redirect_to desc_partner_places_url(params[:partner_id]), notice: 'Place was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @place = Place.find(params[:id])
    if params[:place][:rating_minus].to_i > 0
      params[:place][:rating_minus] = params[:place][:rating_minus].to_i * -1
    end
    if params[:place][:rating_minus].to_i + params[:place][:rating_plus].to_i == 0
      params[:place][:rating] = 0
    else
      params[:place][:rating] = ((params[:place][:rating_plus].to_f / (params[:place][:rating_minus].to_f.abs + params[:place][:rating_plus].to_f.abs)) * 100).round
    end
    if params[:delivery]
      case params[:delivery]
        when "free"
          DeliveryPrice.where(:place_id => params[:id]).destroy_all
        when "region"
          DeliveryPrice.where(:place_id => params[:id]).destroy_all
          params[:delivery_region_new].each do |k, drn|
            if drn[:price] && drn[:price] != ""
              DeliveryPrice.create({:place_id => params[:id], :condition => "region", :price => drn[:price], :region_id => drn[:region]})
            end
          end
      end
    end
    if @place.update_attributes(params[:place])
      redirect_to desc_partner_places_url(params[:partner_id]), notice: 'Place was successfully updated.'
      #render :json => params
    else
      render action: "edit"
    end
  end

  def destroy
    @place = Place.find(params[:id])
    users=[]
    @place.place_accesses.map{|p| users << p.user_id}
    @place.destroy
    users.each do |u|
      setUserAccess u
    end

    redirect_to desc_partner_places_url(params[:partner_id])
  end

end

app/controllers/partner/index_controller.rb
# encoding: utf-8
class Partner::IndexController < ApplicationController
  before_filter :admins, :partners_only, :breds, :title_set
  layout 'partner'

  def title_set
    @title = "Svek.la {свекла}"
    @descr = "Svek.la {свекла} это новый удобный способ заказывать любимую еду и получать за это подарки."
    @title = "Личный кабинет | " + @title
  end


  def index

      @partner_bred=[]
      @partner_bred[0]=['Статистика','/partner']

    @bread = [['Главная']]
    @orders = Order.where('status_id > ?', 62)
    places_ids = partner_admin_places_id
    @ord_yd = @orders.where('created_at >= ? AND created_at <= ?', Time.now.beginning_of_day - 1.day, Time.now.end_of_day - 1.day).where(:place_id => places_ids)
    @ord_td = @orders.where('created_at >= ? AND created_at <= ?', Time.now.beginning_of_day, Time.now.end_of_day).where(:place_id => places_ids)
      @dates=[]
      time=Time.now
      while Time.now-2.years < time  do
        @dates<<[((I18n.t time.strftime("%B"))+time.strftime(" %Y")),time.strftime("%Y-%m-01")]
        time=time-1.month
      end


  end
end

app/controllers/partner/statistics_controller.rb
# encoding: utf-8
class Partner::StatisticsController < ApplicationController

  before_filter :breadcrumbs
  before_filter :authenticate_user!
  before_filter :admins
  before_filter :not_operators, :title_set, :global_orders, :breds
  layout 'partner'

  def global_orders
    global_orders = role_orders
  end

  def title_set
    @title = "Svek.la {свекла}"
    @descr = "Svek.la {свекла} это новый удобный способ заказывать любимую еду и получать за это подарки."
    @title = "Личный кабинет | " + @title
  end

  def breadcrumbs
    @bread = [['Главная', '/desc'], ['Статистика', '/desc/statistics']]
  end

  def index
    @title = "Статистика | " + @title
    @places = Place.find(partner_admin_places_id)
    @orders = Order.where("status_id > ?", 1)
  end

  def show
    @title = "Статистика | " + @title
    @places = Place.find(partner_admin_places_id)
    @orders = Order.where("status_id > ?", 1)
  end

end

app/helpers/desc/places/sections_helper.rb
module Desc::Places::SectionsHelper
end

app/helpers/desc/places_helper.rb
module Desc::PlacesHelper
end

app/helpers/partner/finances_helper.rb
module Partner::FinancesHelper
end

app/helpers/partner/orders_helper.rb
module Partner::OrdersHelper
end

app/helpers/partner/specials_helper.rb
module Partner::SpecialsHelper
end

app/helpers/partners/index_helper.rb
module Partners::IndexHelper
end

app/views/partner/places/_form.html.haml
.alert-heading.alert
  Для изменения информации о ресторане свяжитесь с администратором по почте
  %a{:href=>'mailto:hello@svek.la', :title=>'', :target=>'_blank'}
    hello@svek.la
= form_for @place, :url => @place.id!=nil ? partner_place_path(@place.id) : partner_places_path do |f|
  .form-horizontal
    -if @place.errors.any?
      #error_explanation
        %h2= "#{pluralize(@place.errors.count, "error")} prohibited this desc_place from being saved:"
        %ul
          - @place.errors.full_messages.each do |msg|
            %li= msg
    %fieldset
      -#.control-group
        %label.control-label
          ID
        .controls
          = @place.id!=nil ? @place.id : "new"
      .control-group
        %label.control-label Активность:
        .controls.docs-input-sizes
          %p
            - if @place.active==1
              %font{:color => "green"}Да
            - else
              %font{:color => "red"}Нет
      .control-group
        %label.control-label Лого:
        .controls.docs-input-sizes
          .pull-left
            =# f.file_field :picture, :class=>"span5 margin-right"
          .pull-left.margin-right{:style=>'padding-left: 10px'}
            = image_tag @place.picture.url(:small), :class=>'pull-left margin-right'
      .control-group
        %label.control-label Название:
        .controls.docs-input-sizes
          %p
            %label #{(@place.id!=nil ? @place.name : '')}
      .control-group
        %label.control-label Описание:
        .controls.docs-input-sizes= f.text_area :description, :size => "200x8", :class=>"span5"
      .control-group
        %label.control-label Кухни:
        .controls.docs-input-sizes
          %p
            - for i in 0..@place.kitchens.count-1
              - if i==@place.kitchens.count-1
                =@place.kitchens[i].name
              -else
                =@place.kitchens[i].name + ', '

      .control-group
        %label.control-label Минимальный заказ:
        .controls.docs-input-sizes
          %p
            = @place.id!=nil ? @place.min_order : ''
      .control-group
        %label.control-label Цена доставки:
        .controls.docs-input-sizes
          /= f.text_field :delivery_price, :class=>"span5", :disabled => true
          %p
            = @place.id!=nil ? @place.delivery_price : ''
      .control-group
        %label.control-label Время доставки:
        .controls.docs-input-sizes
          /= f.text_field :delivery_time, :class=>"span5", :disabled => true
          %p
            = @place.id!=nil ? @place.delivery_time : ''
    <div class="alert alert-info"><strong>Внимание!</strong> После сохранения все изменения отобразятся на сайте мгновенно. Тщательно проверьте указанные данные. Спасибо!</div>
    .form-actions.input-height
      = link_to 'Отмена', partner_places_path, :class => "btn btn-large"
      = f.submit 'Сохранить', :class => "btn btn-success btn-large"

app/views/partner/places/_log.html.haml
-if l.order
  %td= l.status.name
  %td= l.user.first_name + ' ' + l.user.last_name
  %td
    =(l.created_at).localtime().strftime("%I")
    \: #{l.created_at.strftime("%M")}
  %td= l.order.place.name
  %td= l.order.price
  %td= l.id

app/views/partner/places/_useredit.html.erb
<%= form_tag '/partner/options/ajaxUserSave/',:class => 'form-horizontal',:id => 'user-form' do%>
    <%= hidden_field_tag :user_id,@u.id.to_s %>
    <%= hidden_field_tag :place_id,@place_id.to_s %>
    <%= hidden_field_tag :reset_password_token %>
    <fieldset>
      <div class="control-group">
        <label class="control-label" for="input01">Имя:</label>
        <div class="controls docs-input-sizes">
          <%= text_field :user, :first_name,:value=>@u.first_name, :class=>'span5' %>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="input01">Фамилия:</label>
        <div class="controls docs-input-sizes">
          <%= text_field :user, :last_name,:value=>@u.last_name, :class=>'span5' %>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="input01">Должность:</label>
        <div class="controls docs-input-sizes">
          <% if @u.id!=current_user.id %>
              <%= select( "add_user_select", "role",{"Администратор"=>"2","Оператор"=>"1"}, {:class=>'span5'}) %>
          <% end %>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="input01">Телефон:</label>
        <div class="controls docs-input-sizes">
          <div class="input-prepend form-inline">
            <span class="add-on">+7</span>
            <%= text_field :user, :phone,:value=>@u.phone.to_s[3..16], :class=>'width-phone' %>
          </div>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="input01">Пароль:</label>
        <div class="controls docs-input-sizes">
          <%= password_field :user, :password, :class=>'span5' %>
        </div>
      </div>
      <div class="form-actions">
        <%= form_tag partner_options_delete_user_path do%>
        <%= hidden_field_tag :user_id,@u.id.to_s %>
        <%= hidden_field_tag :place_id,@place_id.to_s %>
        <a class="btn btn-large" href='/partner/options' title=''>Назад</a>
        <%= submit_tag  'Удалить пользователя',:class=>'btn btn-danger btn-large' %>
        <% end %>
        <%=submit_tag "Сохранить",:class=>'btn btn-large btn-success', :id=>'save_user' %>
      </div>
    </fieldset>
<% end %>

<%#= button_to "Удалить",partner_options_delete_user_path,:user_id => @u.id,:place_id=>@place_id,:confirm => "Точно удалить?" %>

app/views/partner/places/edit.html.haml
= render 'form'

app/views/partner/places/index.html.haml
-#.btn-toolbar#model-bar{:data => {:code => "Item"}}
  .btn-group
    = link_to '<i class="icon-plus icon-white"></i> Новое место' .html_safe, new_partner_place_path, :class => "btn btn-success"
  .btn-group
    %button.btn.disabled Выделенные:
    %button.btn#activate-selected
      %i.icon-ok
      Активировать
    %button.btn#deactivate-selected
      %i.icon-remove
      Деактивировать
    %button.btn.btn-danger#remove-selected
      %i.icon-minus.icon-white
      Удалить
-#.clear
-#%br

%table.table.table-bordered
  %thead
    %tr
      -#%th
        .btn-group
          .btn#button-select-all
            %i.icon-check
          .btn.btn-small.dropdown-toggle{:data => {:toggle => "dropdown"}}
            /%input{:type => "checkbox"}
            %span.caret
          %ul.dropdown-menu
            %li
              %a#select-all{:href => "javascript:;"} Выделить все
            %li
              %a#select-none{:href => "javascript:;"} Снять выделения
            %li
              %a#select-rnd{:href => "javascript:;"} Выделить случайно
            %li
              %a#select-inv{:href => "javascript:;"} Инвертировать выделение
      %th Управление
      %th Название
      %th Город
      %th Описание
      -#%th
      -#%th ID
      -#%th Лого
      -#%th Активность
      -#%th Описание
      -#%th Стоимость доставки
      -#%th Время доставки
      -#%th Минимальный заказ
      -#%th Рейтинг
      -#%th Создан
      -#%th Изменен
      -#%th Меню
      -#%th Акции
      -#%th


  %tbody
  - @places.each do |place|
    %tr
      %td{:style=>'width:230px'}
        .btn-group
          %a.btn{:href=>partner_place_sections_path(place)} <i class="icon-list-alt"></i> Меню
          %a.btn{:href=>partner_place_specials_path(place)} <i class="icon-star"></i> Акции
          %a.btn{:href=>edit_partner_place_path(place)} <i class="icon-pencil"></i> Инфо
        -#.btn-group
          %button.btn.dropdown-toggle{:data => {:toggle => "dropdown"}}
            Действия
            /%i.icon-list
            %span.caret
          %ul.dropdown-menu
            %li= link_to '<i class="icon-list-alt"></i> Меню'.html_safe, partner_place_sections_path(place)
            %li= link_to '<i class="icon-star"></i> Акции'.html_safe, partner_place_specials_path(place)
            %li= link_to '<i class="icon-pencil"></i> Редактировать'.html_safe, edit_partner_place_path(place)
            -#%li= link_to '<i class="icon-remove"></i> Удалить'.html_safe, partner_place_path(place), :confirm => 'Действительно удалить?', :method => :delete
      %td{:style=>'width:150px'}= place.name
      %td{:style=>'width:150px'}= place.city.name
      %td= place.description

      -#%td
        %input{:type => "checkbox"}
      -#%td= place.id
      -#%td
        %img{:src => place.picture(:mini)}
      -#%td= place.active
      -#%td= place.description
      -#%td= place.delivery_price
      -#%td= place.delivery_time
      -#%td= place.min_order
      -#%td= place.rating
      -#%td= place.created_at
      -#%td= place.updated_at


app/views/partner/places/index_old.html.erb
<h2>Рестораны</h2>
<table>
  <thead>
      <tr>
        <th>Название</th>
        <th>Категория</th>
        <th>заказы</th>
        <th>Сумма(руб.)</th>
      </tr>
  </thead>
   <tbody>
   <% @places.each do |p| %>
   <tr onclick="location.href='<%= partner_place_sections_path(p.id) %>'">
     <td><%= p.name %></td>
     <td><%= p.name %></td>
     <td><%= p.orders.count %></td>
     <td><%= p.orders.sum(:price).ceil  %></td>
   </tr>
   <% end %>
   </tbody>
</table>


    <%#=link_to p.name, partner_place_path(p.id)  %>

app/views/partner/places/new.html.haml
= render 'form'
-#= link_to 'Назад',  partner_finances_path


app/views/partner/places/show.html.erb
SHow <%= @place.name %>   <br>
Категории: <br>
<% @sections.each do |s| %>
<%= link_to s.name + ' (' + s.cnt.to_s + ')', partner_place_section_path(params[:id],s.id) %>  <br>
<% end %>
<br>
<%= link_to 'Создать',   new_partner_place_section_path(params[:id]) %>
<br>
<%= link_to 'Назад', '/partner' %>