config/routes.rb
Delivery::Application.routes.draw do

  get "/desc" => "desc/orders#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => 'index#index'

  match '/404' => 'index#not_found'
  match '/success/:id' => 'index#success'
  match '/place/:id' => 'index#place'
  match "/ajax/:action" => 'ajax'
  match '/forms/:action' => 'forms'
  match '/license' => 'index#license'
  match '/partnership' => 'index#partnership'
  match '/vacancy' => 'index#vacancy'
  match '/contact' => 'index#contact'
  match '/welcome' => 'index#welcome'
  match '/gifts' => 'index#gifts'

  match '/profile/:action' => 'profile'
  match '/profile' => 'profile#info'
  match '/profile/gifts' => 'index#userGifts'

  match '/partner' => 'partner/orders#index'
  match '/partner/orders/:order_id/ajaxEdit' => 'partner/orders#ajaxEdit'
  match '/partner/orders/:order_id/ajax_roll_back' => 'partner/orders#ajax_roll_back'
  match '/partner/orders/sortIndex' => 'partner/orders#sortIndex'
  match '/partner/orders/ajaxPaginate' => 'partner/orders#ajaxPaginate'
  match '/partner/orders/:order_id/ajaxRecover' => 'partner/orders#ajaxRecover'
  match '/partner/orders/:order_id/ajaxAdopted' => 'partner/orders#ajaxAdopted'
  match '/desc/orders/:order_id/ajaxEdit' => 'desc/orders#ajaxEdit'
  match '/desc/orders/sortIndex' => 'desc/orders#sortIndex'
  match '/desc/orders/ajaxPaginate' => 'desc/orders#ajaxPaginate'
  match '/desc/orders/ajaxIndex'=>'desc/orders#ajaxIndex'
  match '/desc/orders/:order_id/ajaxChangeAddress'=>'desc/orders#ajaxChangeAddress'

  match '/desc/orders/:order_id/ajax_roll_back'=>'desc/orders#ajax_roll_back'
  match '/desc/orders/:order_id/ajaxRecover' => 'desc/orders#ajaxRecover'
  match '/desc/orders/:order_id/ajaxAdopted' => 'desc/orders#ajaxAdopted'
  namespace :partner do
    root :to => 'orders#index'
    match "/ajax/:action" => 'ajax'
    get 'options' => 'places#options'
    get 'options/ajaxOptions' => 'places#ajaxOptions'
    match 'options/addUser' => 'places#addUser'
    post 'options/ajaxUserSave/' => 'places#ajaxUserSave'
    get 'options/ajaxOptionsUsers' => 'places#ajaxOptionsUsers'
    get 'options/ajaxUserEdit' => 'places#ajaxUserEdit'
    match 'options/delete_user' => 'places#delete_user'
    match 'options/setAlerts' => 'places#setAlerts'
    get 'options/accordion' => 'places#accordion'
    #match 'options/ajaxhistory' => 'places#ajaxhistory'
    match 'finances/ajaxPrice'=>'finances#ajaxPrice'
    match 'finances/ajaxIndex'=>'finances#ajaxIndex'
    match 'finances/ajaxBreadcrumb'=>'finances#ajaxBreadcrumb'
    #match 'finances/:id/render_to_xls' =>'finances#render_to_xls'

    #match "/ajax/:action" => 'ajax'
    match "/statistics/:action" => 'statistics'
    match "/statistics" => 'statistics#index'

    resources :finances
    resources :orders do
      get 'ajaxAdd'
      match 'ajaxSubmit'
      match 'ajaxTransfer'
      match 'ajaxCancel'
      match 'ajaxDeliver'
    end
    resources :places do
      #end
      match 'specials/showPic' => 'specials#showPic'
      resources :specials
      resources :sections do
        resources :items
      end
    end
  end

=begin
  namespace :operator do
    resources :orders do
      get 'ajaxAdd'
      match 'submit'
      match 'transmit'
      match 'cancel_order'
      match 'cancel_submit'
    end
    resources :places do
    end
  end
=end

  namespace :desc do
    root :to => "desc#orders"
    match "/ajax/:action" => 'ajax'
    match "/statistics/:action" => 'statistics'
    #match "/statistics/:action/:tab" => 'statistics'
    match "/statistics" => 'statistics#index'
    resources :users
    resources :cities do
      resources :regions
      resources :metros
    end
    resources :orders do
      #match '' orders_region_id_select
      match 'ajaxAdd'
      match 'ajaxSubmit'
      match 'ajaxTransfer'
      match 'ajaxCancel'
      match 'ajaxDeliver'
    end
    match 'finances/ajaxPrice'=>'finances#ajaxPrice'
    match 'finances/ajaxIndex'=>'finances#ajaxIndex'
    match 'finances/ajaxBreadcrumb'=>'finances#ajaxBreadcrumb'
    match 'finances/:id/render_to_xls' =>'finances#render_to_xls'
    match 'finances/:id/send_report' =>'finances#send_report'
    match 'finances/:id/send_called_report' =>'finances#send_called_report'
    resources :finances
    resources :kitchens
    resources :specials
    resources :populars
    resources :partners do
      resources :places do
        resources :sections do
          resources :items
        end
      end
    end
    resources :gift_sections do
      resources :gifts
    end
    resources :usergifts
  end
  match "*path", :to => "application#not_found"
end

app/models/place.rb
class Place < ActiveRecord::Base
  scope :activated, where(:active => 1)
  belongs_to :partner
  has_and_belongs_to_many :kitchens
  has_many :orders
  has_many :users
  has_many :finances, :dependent => :delete_all
  has_many :specials, :dependent => :delete_all
  has_many :sections, :dependent => :destroy
  has_many :orders, :dependent => :destroy
  has_many :place_accesses, :dependent => :delete_all
  has_many :delivery_prices, :dependent => :delete_all


  has_attached_file :picture,
                    :url => :default_url,
                    :path => :default_path,
                    :styles => {:large => "x400", :normal => "x200", :small => "135x250", :mini => "x30", :index => "220x220"}
  belongs_to :city

  #def delit
  #  Section.where(:place_id=>self.id).each do |s|
  #    s.delit
  #  end
  #  Orders.where(:place_id=>self.id).each do |o|
  #    o.delit
  #  end
  #  self.destroy
  #end

  private
  def default_url
    "/picture/place/"+self.id.to_s+ "/:style/:basename.:extension"
  end

  def default_path
    ":rails_root/public/picture/place/"+self.id.to_s+"/:style/:basename.:extension"
  end

end

app/controllers/desc/ajax_controller.rb
# encoding: utf-8

class Desc::AjaxController < ApplicationController

  before_filter :global_operators
  layout 'nil'

  def chart_orders
    ser_guest = {:name => "Гости", :data => []}
    ser_auth = {:name => "Пользователи", :data => []}
    cats = []
    guest_count = 0
    auth_count = 0
    s_d = nil
    if params[:period] == "yesterday"
      orders = Order.where("status_id > ? AND created_at >= ? AND created_at <= ?", 1, Time.now.beginning_of_day - 1.day, Time.now.end_of_day - 1.day).order("created_at ASC")
      if orders.exists?
        s_d = orders.first.created_at.hour
        orders.each do |ord|
          if ord.created_at.hour != s_d
            ser_guest[:data] << guest_count
            ser_auth[:data] << auth_count
            cats << s_d
            guest_count = 0
            auth_count = 0
          end
          if ord.user_id > 0
            auth_count += 1
          else
            guest_count += 1
          end
          s_d = ord.created_at.hour
        end
      end
    end
    if params[:period] == "day"
      orders = Order.where("status_id > ? AND created_at >= ? AND created_at <= ?", 1, Time.now.beginning_of_day, Time.now.end_of_day).order("created_at ASC")
      if orders.exists?
        s_d = orders.first.created_at.hour
        orders.each do |ord|
          if ord.created_at.hour != s_d
            ser_guest[:data] << guest_count
            ser_auth[:data] << auth_count
            cats << s_d
            guest_count = 0
            auth_count = 0
          end
          if ord.user_id > 0
            auth_count += 1
          else
            guest_count += 1
          end
          s_d = ord.created_at.hour
        end
      end
    end
    if params[:period] == "week"
      orders = Order.where("status_id > ? AND created_at >= ? AND created_at <= ?", 1, Time.now.beginning_of_week, Time.now.end_of_week).order("created_at ASC")
      if orders.exists?
        s_d = orders.first.created_at.wday
        orders.each do |ord|
          if ord.created_at.wday != s_d
            ser_guest[:data] << guest_count
            ser_auth[:data] << auth_count
            cats << s_d
            guest_count = 0
            auth_count = 0
          end
          if ord.user_id > 0
            auth_count += 1
          else
            guest_count += 1
          end
          s_d = ord.created_at.wday
        end
      end
    end
    if params[:period] == "month"
      orders = Order.where("status_id > ? AND created_at >= ? AND created_at <= ?", 1, Time.now.beginning_of_month, Time.now.end_of_month).order("created_at ASC")
      if orders.exists?
        s_d = orders.first.created_at.day
        orders.each do |ord|
          if ord.created_at.day != s_d
            ser_guest[:data] << guest_count
            ser_auth[:data] << auth_count
            cats << s_d
            guest_count = 0
            auth_count = 0
          end
          if ord.user_id > 0
            auth_count += 1
          else
            guest_count += 1
          end
          s_d = ord.created_at.day
        end
      end
    end
    if params[:period] == "quarter"
      orders = Order.where("status_id > ? AND created_at >= ? AND created_at <= ?", 1, Time.now.beginning_of_quarter, Time.now.end_of_quarter).order("created_at ASC")
      if orders.exists?
        s_d = orders.first.created_at.day
        orders.each do |ord|
          if ord.created_at.day != s_d
            ser_guest[:data] << guest_count
            ser_auth[:data] << auth_count
            cats << s_d
            guest_count = 0
            auth_count = 0
          end
          if ord.user_id > 0
            auth_count += 1
          else
            guest_count += 1
          end
          s_d = ord.created_at.day
        end
      end
    end
    if params[:period] == "year"
      orders = Order.where("status_id > ? AND created_at >= ? AND created_at <= ?", 1, Time.now.beginning_of_year, Time.now.end_of_year).order("created_at ASC")
      if orders.exists?
        s_d = orders.first.created_at.day
        orders.each do |ord|
          if ord.created_at.day != s_d
            ser_guest[:data] << guest_count
            ser_auth[:data] << auth_count
            cats << s_d
            guest_count = 0
            auth_count = 0
          end
          if ord.user_id > 0
            auth_count += 1
          else
            guest_count += 1
          end
          s_d = ord.created_at.day
        end
      end
    end
    if !cats.include?(s_d)
      ser_guest[:data] << guest_count
      ser_auth[:data] << auth_count
      cats << s_d
    end

    render :json => {
        :series => [ser_guest, ser_auth],
        :categories => cats
    }

    #render :json => orders.map{|o| [o.id, o.user_id, o.created_at.wday, o.created_at.beginning_of_year, o.created_at.end_of_year]}

  end

  def order_sum
    orders = Order.where('status_id > 1')
    case params[:period]
      when "yesterday"
        orders = orders.where('created_at > ? AND created_at < ?', Time.now.beginning_of_day - 1.day, Time.now.end_of_day - 1.day)
      when "day"
        orders = orders.where('created_at > ? AND created_at < ?', Time.now.beginning_of_day, Time.now.end_of_day)
      when "week"
        orders = orders.where('created_at > ? AND created_at < ?', Time.now.beginning_of_week, Time.now.end_of_week)
      when "month"
        orders = orders.where('created_at > ? AND created_at < ?', Time.now.beginning_of_month, Time.now.end_of_month)
      when "quarter"
        orders = orders.where('created_at > ? AND created_at < ?', Time.now.beginning_of_quarter, Time.now.end_of_quarter)
      when "year"
        orders = orders.where('created_at > ? AND created_at < ?', Time.now.beginning_of_year, Time.now.end_of_year)
    end
    @ord_delivered = orders.where('status_id = 100')
    @ord_user_cancel = orders.where('status_id = 20')
    @ord_rest_cancel = orders.where('status_id = 80')
  end

  def places_top
    case params[:period]
      when "yesterday"
        @places = Place.select("places.name, SUM(orders.price) AS orders_sum, COUNT(orders.id) as orders_count").joins(:orders).where("orders.status_id = 100").where('orders.created_at >= ? AND orders.created_at <= ?', Time.now.beginning_of_day - 1.day, Time.now.end_of_day - 1.day).group("places.id").order("orders_count DESC, orders_sum DESC")
      when "day"
        @places = Place.select("places.name, SUM(orders.price) AS orders_sum, COUNT(orders.id) as orders_count").joins(:orders).where("orders.status_id = 100").where('orders.created_at >= ? AND orders.created_at <= ?', Time.now.beginning_of_day, Time.now.end_of_day).group("places.id").order("orders_count DESC, orders_sum DESC")
      when "week"
        @places = Place.select("places.name, SUM(orders.price) AS orders_sum, COUNT(orders.id) as orders_count").joins(:orders).where("orders.status_id = 100").where('orders.created_at >= ? AND orders.created_at <= ?', Time.now.beginning_of_week, Time.now.end_of_week).group("places.id").order("orders_count DESC, orders_sum DESC")
      when "month"
        @places = Place.select("places.name, SUM(orders.price) AS orders_sum, COUNT(orders.id) as orders_count").joins(:orders).where("orders.status_id = 100").where('orders.created_at >= ? AND orders.created_at <= ?', Time.now.beginning_of_month, Time.now.end_of_month).group("places.id").order("orders_count DESC, orders_sum DESC")
      when "quarter"
        @places = Place.select("places.name, SUM(orders.price) AS orders_sum, COUNT(orders.id) as orders_count").joins(:orders).where("orders.status_id = 100").where('orders.created_at >= ? AND orders.created_at <= ?', Time.now.beginning_of_quarter, Time.now.end_of_quarter).group("places.id").order("orders_count DESC, orders_sum DESC")
      when "year"
        @places = Place.select("places.name, SUM(orders.price) AS orders_sum, COUNT(orders.id) as orders_count").joins(:orders).where("orders.status_id = 100").where('orders.created_at >= ? AND orders.created_at <= ?', Time.now.beginning_of_year, Time.now.end_of_year).group("places.id").order("orders_count DESC, orders_sum DESC")
    end
  end

  def edit
    if params[:id] && params[:model] && params[:field] && params[:val]
      cl = eval(params[:model])
      res = cl.find(params[:id])
      res.each do |r|
        r.update_attribute params[:field], params[:val]
      end
      render :json => {:stat => "ok"}
    else
      render :json => {:stat => "error", :text => "error"}
    end
  end

  def remove
    if params[:id] && params[:model]
      cl = eval(params[:model])
      res = cl.find(params[:id])
      res.each do |r|
        r.destroy
      end
      render :json => {:stat => "ok"}
    else
      render :json => {:stat => "error", :text => "error"}
    end
  end

  def get_regions
    if params[:city]
      regions = Region.where(:city_id => params[:city])
      render :json => {:stat => "ok", :regions => regions}
    else
      render :json => {:stat => "error"}
    end
  end

  def get_metros
    if params[:city]
      metros = Metro.where(:city_id => params[:city])
      render :json => {:stat => "ok", :regions => metros}
    else
      render :json => {:stat => "error"}
    end
  end

  def reset_password
    if User.where(:id => params[:uid]).exists?
      user = User.find(params[:uid])
      password = 100000 + rand(899999)
      user.password = password
      user.save
      mess = {}

      LittleSMS.new(SMS_USER, SMS_KEY) do
        msg = message.send(:recipients => user.phone.to_s, :message => "Новый пароль для доступа в личный кабинет Svek.la: " + password.to_s, :sender => SMS_SENDER)
        if msg.error?
          mess = {:stat => "error", :text => msg.message}
        else
          mess = {:stat => "ok", :phone => user.phone, :msg_text => t(:sms_message_send), :text => t(:sms_message_send)}
        end
      end
    else
      mess = {:stat => "error", :text => t(:user_not_exist)}
    end
    respond_to do |format|
      format.json { render json: mess }
    end

app/controllers/desc/cities_controller.rb
# encoding: utf-8
class Desc::CitiesController < ApplicationController

  before_filter :global_admins, :breadcrumbs
  layout 'desc'

  def breadcrumbs
    @bread = [['Главная', '/desc'], ['Города', desc_cities_path]]
  end

  def index
    if params[:f] && params[:d]
      @cities = City.order(params[:f] + " " + params[:d])
    else
      @cities = City.all
    end
  end

  def show
    @city = City.find(params[:id])
  end

  def new
    @city = City.new
  end

  def edit
    @city = City.find(params[:id])
  end

  def create
    @city = City.new(params[:city])
    if @city.save
      redirect_to desc_cities_url, notice: 'City was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @city = City.find(params[:id])
    if @city.update_attributes(params[:city])
      redirect_to desc_cities_url, notice: 'City was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @city = City.find(params[:id])
    @city.destroy
    redirect_to desc_cities_url
  end
end

app/controllers/desc/statistics_controller.rb
# encoding: utf-8
class Desc::StatisticsController < ApplicationController

  before_filter :global_admins, :breadcrumbs, :get_vars
  layout 'desc'

  def get_vars
    @places = Place.where(:active => 1)
    @orders = Order.where("status_id > ?", 1)
  end

  def breadcrumbs
    @bread = [['Главная', '/desc'], ['Статистика', '/desc/statistics']]
  end

  def index
  end

  def show
  end

  def orders_count
    @bread << ['Заказы']
  end

  def orders_summ
    @bread << ['Сумма']
  end

  def populars
    @bread << ['Популярные']
  end

end

app/views/desc/places/_form.html.haml
= form_for @place, :url => @place.id!=nil ? desc_partner_place_path(params[:partner_id], @place.id) : desc_partner_places_path(params[:partner_id]) do |f|
  -if @place.errors.any?
    #error_explanation
      %h2= "#{pluralize(@place.errors.count, "error")} prohibited this desc_place from being saved:"
      %ul
        - @place.errors.full_messages.each do |msg|
          %li= msg
  .form-horizontal
    %fieldset
      .control-group
        %label.control-label
          Официальное название:
        .controls
          = f.text_field :name, :class=>'span5'
      .control-group
        %label.control-label
          ID:
        .controls
          %input{:type=>'text', :class=>'span1', :value=> @place.id!=nil ? @place.id : "new"}
      .control-group
        %label.control-label
          Активность:
        .controls
          = f.check_box :active, :checked => @place.id==nil ? true : @place.active ? true : false
      .control-group
        %label.control-label
          Лого:
        .controls
          .pull-left
            = f.file_field :picture, :class=>"span5 margin-right"
          .pull-left.margin-right{:style=>'padding-left: 10px'}
            = @place.picture? ? image_tag(@place.picture.url(:small)) : ""

      .control-group
        %label.control-label
          Описание:
        .controls
          = f.text_area :description, :size => "200x8", :class=>'span5'
      .control-group
        %label.control-label
          Кухни:
        .controls
          = f.select(:kitchen_ids, options_from_collection_for_select(Kitchen.all, :id, :name, @place.kitchens.map{|k| k.id}), {}, {:multiple=>"multiple", :class=>'multi span5', :size=>'20' })
          <span class="help-inline" style="width: 410px; text-align: left;">Для выбора нескольких позиций зажмите клавишу <strong>ctrl</strong> и нажмите мышкой на нужные позиции.</span>


      .control-group
        %label.control-label
          Рейтинг кол-во "-"
        .controls
          = f.text_field :rating_minus, :class => 'span1'
      .control-group
        %label.control-label
          Рейтинг кол-во "+"
        .controls
          = f.text_field :rating_plus, :class => 'span1'


      .control-group
        %label.control-label
          Минимальный заказ
        .controls
          = f.text_field :min_order, :class => 'span1'
          руб.
      .control-group
        %label.control-label
          Время доставки
        .controls
          = f.text_field :delivery_time, :class => 'span1'
          минут
      .control-group
        %label.control-label
          Город:
        .controls
          = f.select(:city_id, City.all.map{|i| [i.name,i.id]})
      .control-group
        %label.control-label
          Стоимость доставки:
        .controls
          = f.text_field :delivery_price, :class => 'span1'
          руб.
      .control-group
        %label.control-label
          Доставка в регионы:
        .controls
          .box
            %input.radio{:type=>'radio', :value=>'free', :name=>'delivery', :checked => true}
            %span Нет
          -#.box
            %input.radio{:type=>'radio', :value=>'', :name=>'delivery'}
            %span Платно
          -#.box
            %input.radio{:type => 'radio', :value => 'static', :name => 'delivery'}
            %span Статичная цена:
            %input.span1{:type => 'text', :value => '', :name => 'static_delivery_price'}
          -#.box
            %input.radio{:type => 'radio', :value => 'variable', :name => 'delivery'}
            %span Переменная цена, от суммы заказа:
          -#.box.ml
            %span если цена меньше
            %input.span1{:type => 'text', :value => '', :name => 'min_order_price'}
            %span , то доставка
            %input.span1{:type => 'text', :value => '', :name => 'variable_delivery_price'}
          -#.box.ml
            %span если цена больше
            %input.span1{:type => 'text', :value => ''}
            %span, то доставка
            %input.span1{:type=>'text', :value=>''}
          .box
            %input.radio{:type => 'radio', :value => 'region', :name => 'delivery', :checked => @place.delivery_prices.to_regions.exists? ? true : false}
            %span В зависимости от региона:
          -#.box.ml
            %span Для всех регионов доставка
            %input.span1{:type => 'text', :value => ''}
          -#.box.ml
            %span кроме:
          .box.ml
            - cnt = 1
            - if @place.delivery_prices.to_regions.exists?
              - @place.delivery_prices.to_regions.each do |dp|
                - cnt += dp.id
                .label-box.edit-box-delivery-region
                  %select.span2.select-delivery-region-edit{:name => "delivery_region_new[#{dp.id}][region]"}
                    - dp.region.city.regions.each do |reg|
                      %option{:value => reg.id, :selected => reg.id == dp.region_id ? true : false}= reg.name
                  %input.span1{:type => 'text', :value => dp.price, :name => "delivery_region_new[#{dp.id}][price]"}
                  #button-del.btn.button-delivery-region-del
                    %i.icon-remove
                .clear
            .label-box.new-box-delivery-region.hide
              %select.span2.select-delivery-region{:name => "delivery_region_new[#{cnt}][region]"}
              %input.span1{:type => 'text', :value => '', :name => "delivery_region_new[#{cnt}][price]"}
              руб.
            .clear
            %input.btn#add-select-input{:type => 'button', :value => "Добавить район"}
      .form-actions
        = link_to 'Отмена', desc_partner_places_path(params[:partner_id]), :class => "btn btn-large"
        = f.submit 'Сохранить', :class => "btn btn-success btn-large"

app/views/desc/places/edit.html.haml
= render 'form'

app/views/desc/places/index.html.haml
.btn-toolbar.margin-bottom#model-bar{:data => {:code => "Place"}}
  .btn-group
    = link_to '<i class="icon-plus icon-white"></i> Новое заведение'.html_safe, new_desc_partner_place_path(params[:partner_id]), :class => "btn btn-success"
  .btn-group
    %button.btn.disabled Выделенные:
    %button.btn#activate-selected
      %i.icon-ok
      Активировать
    %button.btn#deactivate-selected
      %i.icon-remove
      Деактивировать
    %button.btn.btn-danger#remove-selected
      %i.icon-minus.icon-white
      Удалить
.clear
%br

%table.table.table-bordered.table-striped.name-width
  %thead
    %tr
      %th
        .btn-group
          .btn.btn-small#button-select-all
            %i.icon-check
          .btn.btn-small.dropdown-toggle{:data => {:toggle => "dropdown"}}
            /%input{:type => "checkbox"}
            %span.caret
          %ul.dropdown-menu
            %li
              %a#select-all{:href => "javascript:;"} Выделить все
            %li
              %a#select-none{:href => "javascript:;"} Снять выделения
            %li
              %a#select-rnd{:href => "javascript:;"} Выделить случайно
            %li
              %a#select-inv{:href => "javascript:;"} Инвертировать выделение
      %th
        .btn.btn-small.disabled Меню
      %th
        .btn.btn-small.disabled Лого
      %th
        %a.btn.btn-small{:href => params[:d] == "desc" ? to_path(params.merge({:f => "id", :d => "asc"})) : to_path(params.merge({:f => "id", :d => "desc"}))}
          ID
          - if params[:f] == "id" || !params[:f]
            - if params[:d] == "desc"
              %i.icon-chevron-up
            - else
              %i.icon-chevron-down
      %th
        %a.btn.btn-small{:href => params[:d] == "desc" ? to_path(params.merge({:f => "name", :d => "asc"})) : to_path(params.merge({:f => "name", :d => "desc"}))}
          Название
          - if params[:f] == "name"
            - if params[:d] == "desc"
              %i.icon-chevron-up
            - else
              %i.icon-chevron-down
      %th
        %a.btn.btn-small{:href => params[:d] == "desc" ? to_path(params.merge({:f => "active", :d => "asc"})) : to_path(params.merge({:f => "active", :d => "desc"}))}
          Активность
          - if params[:f] == "active"
            - if params[:d] == "desc"
              %i.icon-chevron-up
            - else
              %i.icon-chevron-down
      %th
        %a.btn.btn-small{:href => params[:d] == "desc" ? to_path(params.merge({:f => "city_id", :d => "asc"})) : to_path(params.merge({:f => "city_id", :d => "desc"}))}
          Город
          - if params[:f] == "city_id"
            - if params[:d] == "desc"
              %i.icon-chevron-up
            - else
              %i.icon-chevron-down
      -#%th
        %a.btn.btn-small{:href => params[:d] == "desc" ? to_path(params.merge({:f => "delivery_price", :d => "asc"})) : to_path(params.merge({:f => "delivery_price", :d => "desc"}))}
          Стоимость дост.
          - if params[:f] == "delivery_price"
            - if params[:d] == "desc"
              %i.icon-chevron-up
            - else
              %i.icon-chevron-down
      -#%th
        %a.btn.btn-small{:href => params[:d] == "desc" ? to_path(params.merge({:f => "delivery_time", :d => "asc"})) : to_path(params.merge({:f => "delivery_time", :d => "desc"}))}
          Время дост.
          - if params[:f] == "delivery_time"
            - if params[:d] == "desc"
              %i.icon-chevron-up
            - else
              %i.icon-chevron-down
      %th
        %a.btn.btn-small{:href => params[:d] == "desc" ? to_path(params.merge({:f => "min_order", :d => "asc"})) : to_path(params.merge({:f => "min_order", :d => "desc"}))}
          Мин. заказ
          - if params[:f] == "min_order"
            - if params[:d] == "desc"
              %i.icon-chevron-up
            - else
              %i.icon-chevron-down
      %th
        %a.btn.btn-small{:href => params[:d] == "desc" ? to_path(params.merge({:f => "rating", :d => "asc"})) : to_path(params.merge({:f => "rating", :d => "desc"}))}
          Рейтинг
          - if params[:f] == "rating"
            - if params[:d] == "desc"
              %i.icon-chevron-up
            - else
              %i.icon-chevron-down
  %tbody
  - @places.each do |place|
    %tr
      %td.small
        %input.select-box{:type => "checkbox", :data => {:id => place.id}}
      %td.small
        .btn-group
          %a.btn{:href => desc_partner_place_sections_path(params[:partner_id], place.id)} Меню
          %button.btn.btn-small.dropdown-toggle{:data => {:toggle => "dropdown"}}
            %i.icon-list
            %span.caret
          %ul.dropdown-menu
            %li= link_to '<i class="icon-signal"></i> Меню'.html_safe, desc_partner_place_sections_path(params[:partner_id], place.id)
            %li= link_to '<i class="icon-user"></i> Пользователи'.html_safe, desc_users_path + "?place=" + place.id.to_s
            %li.divider
            %li= link_to '<i class="icon-pencil"></i> Редактировать'.html_safe, edit_desc_partner_place_path(params[:partner_id], place.id)
            %li= link_to '<i class="icon-remove"></i> Удалить'.html_safe, desc_partner_place_path(params[:partner_id], place.id), :confirm => 'Вы уверены?', :method => :delete
      %td
        %img{:src => place.picture(:mini)}
      %td= place.id
      %td= place.name
      %td= place.active==1 ? '<span style="color:green;">Да</span>'.html_safe : '<span style="color:red;">Нет</span>'.html_safe
      %td= place.city ? link_to(place.city.name.to_s + " (" + place.city.id.to_s + ")", edit_desc_city_path(place.city)) : ""
      /%td= place.delivery_price
      /%td= place.delivery_time
      %td= place.min_order
      %td= place.rating

app/views/desc/places/new.html.haml
= render 'form'

app/views/desc/places/show.html.haml
%p#notice= notice

= link_to 'Edit', edit_desc_place_path(@desc_place)
\|
= link_to 'Back', desc_places_path